In [5]:
import pandas

In [6]:
df= pandas.read_csv("E:\Sem-1 UIC\IDS-570\Session 3\cars.csv")

In [7]:
df

      year model   price  mileage   color transmission       date
0    2,011   SEL  21,992    7,413  Yellow         AUTO   2-May-13
1    2,011   SEL  20,995   10,926    Gray         AUTO   3-May-13
2    2,011   SEL  19,995    7,351  Silver         AUTO   4-May-13
3    2,011   SEL  17,809   11,613    Gray         AUTO   5-May-13
4    2,012    SE  17,500    8,367   White         AUTO   6-May-13
5    2,010   SEL  17,495   25,125  Silver         AUTO   7-May-13
6    2,011   SEL  17,000   27,393    Blue         AUTO   8-May-13
7    2,010   SEL  16,995   21,026  Silver         AUTO   9-May-13
8    2,011   SES  16,995   32,655  Silver         AUTO  10-May-13
9    2,010   SES  16,995   36,116  Silver         AUTO  11-May-13
10   2,010   SES  16,995   40,539   Black         AUTO  12-May-13
11   2,011   SES  16,992    9,199  Silver         AUTO  13-May-13
12   2,011   SEL  16,950    9,388   Green         AUTO  14-May-13
13   2,010   SES  16,950   32,058     Red         AUTO  15-May-13
14   2,011    SE  16,000   15,367   White         AUTO  16-May-13
15   2,011   SES  15,999   16,368    Blue         AUTO  17-May-13
16   2,010   SEL  15,999   19,926  Silver         AUTO  18-May-13
17   2,010   SES  15,995   36,049  Silver         AUTO  19-May-13
18   2,011   SEL  15,992   11,662    Blue         AUTO  20-May-13
19   2,011   SEL  15,992   32,069  Silver         AUTO  21-May-13
20   2,010   SES  15,988   16,035  Silver       MANUAL  22-May-13
21   2,010   SEL  15,980   39,943   White         AUTO  23-May-13
22   2,011    SE  15,899   36,685  Silver         AUTO  24-May-13
23   2,010   SEL  15,889   24,920   Black         AUTO  25-May-13
24   2,009   SEL  15,688   20,019    Blue         AUTO  26-May-13
25   2,010    SE  15,500   29,338    Blue         AUTO  27-May-13
26   2,010    SE  15,499    7,784   Black         AUTO  28-May-13
27   2,010    SE  15,499   35,636   Black         AUTO  29-May-13
28   2,010   SES  15,298   22,029    Gray         AUTO  30-May-13
29   2,009   SEL  14,999   33,107  Silver         AUTO  31-May-13
..     ...   ...     ...      ...     ...          ...        ...
120  2,010    SE  10,717   64,199   Black         AUTO  30-Aug-13
121  2,007   SES  10,000   63,926     Red         AUTO  31-Aug-13
122  2,007   SES   9,999   74,427  Silver         AUTO   1-Sep-13
123  2,007   SES   9,999   78,948   Black       MANUAL   2-Sep-13
124  2,006    SE   9,995   51,311  Silver         AUTO   3-Sep-13
125  2,008    SE   9,995   95,364   White         AUTO   4-Sep-13
126  2,008    SE   9,992   74,109   White         AUTO   5-Sep-13
127  2,007    SE   9,651   63,296    Blue         AUTO   6-Sep-13
128  2,007   SES   9,000   80,605     Red         AUTO   7-Sep-13
129  2,006    SE   8,999   49,656  Silver         AUTO   8-Sep-13
130  2,007    SE   8,996   48,652  Silver       MANUAL   9-Sep-13
131  2,006    SE   8,800   71,331   White         AUTO  10-Sep-13
132  2,008    SE   8,495  106,171   Black         AUTO  11-Sep-13
133  2,008    SE   8,494   68,901  Silver         AUTO  12-Sep-13
134  2,009    SE   8,480   70,036   White       MANUAL  13-Sep-13
135  2,007   SES   7,999   81,596  Yellow       MANUAL  14-Sep-13
136  2,006   SES   7,995   35,000   Black       MANUAL  15-Sep-13
137  2,006   SES   7,995   97,987     Red         AUTO  16-Sep-13
138  2,003   SES   7,900   96,000   White         AUTO  17-Sep-13
139  2,005   SES   7,488   59,013     Red         AUTO  18-Sep-13
140  2,004    SE   6,999  105,714  Silver         AUTO  19-Sep-13
141  2,007    SE   6,995   86,862   White         AUTO  20-Sep-13
142  2,000    SE   6,980   60,161   Green         AUTO  21-Sep-13
143  2,004   SES   6,980  101,130    Gray         AUTO  22-Sep-13
144  2,004   SES   6,950  119,720   Black         AUTO  23-Sep-13
145  2,006   SES   6,200   95,000  Silver         AUTO  24-Sep-13
146  2,002    SE   5,995   87,003     Red         AUTO  25-Sep-13
147  2,000    SE   5,980   96,841     Red         AUTO  26-Sep-13
148  2,001    SE   4,899  151,479  Yellow         AUTO  27-Sep-13
149  2,000    SE   3,800  109,259     Red         AUTO  28-Sep-13

[150 rows x 7 columns]